htop: remove "-pedantic"
error: external/htop/Android.bp:68:11: module "htop" variant "android_arm64_armv8-a_cortex-a73": cflags: Illegal flag `-pedantic`

This is deemed an illegal flag as of I3885de831e95aeeca2ca5c0f03434e26a05c6403, remove it.

Change-Id: I38b9a9d40646d46d18723b8a2eb2ba313f021c9e